#!/bin/bash

SRC_DIR="$( cd -P "$( dirname "$0" )" && pwd )"

# Note: you must rebuild remotely if you change remote-config.sh

### BEGIN Editable part

REMOTE_USER_ROUTER='root'
# IP address of the network emulator (the machine running line-router)
# For a hostname, you can use "$(host the.host.name | cut -d ' ' -f 4)"
REMOTE_HOST_ROUTER="TODO TO BE FILLED IN!!!"
REMOTE_PORT_ROUTER='22'
REMOTE_DEDICATED_IP_ROUTER='192.168.77.1'
REMOTE_DEDICATED_IF_ROUTER='TODO TO BE FILLED IN!!!'

# For a debug build of line-router:
#BUILD_CONFIG_ROUTER='CONFIG-=release\ CONFIG+=debug'
# For a release build:
BUILD_CONFIG_ROUTER='CONFIG+=release\ CONFIG-=debug'

# This needs to be done only once (unless you change the PF_RING sources or upgrade the kernel).
# Set INSTALL_PF_RING to false to speed up the installation of line-router
INSTALL_PF_RING=true
#INSTALL_PF_RING=false

REMOTE_USER_HOSTS='root'
# IP address of the traffic generator (the machine running line-traffic)
# For a hostname, you can use "$(host the.host.name | cut -d ' ' -f 4)"
REMOTE_HOST_HOSTS="TODO TO BE FILLED IN!!!"
REMOTE_PORT_HOSTS='22'
REMOTE_DEDICATED_IP_HOSTS='192.168.77.2'
REMOTE_DEDICATED_IF_HOSTS='TODO TO BE FILLED IN!!!'

# For a debug build of line-traffic:
#BUILD_CONFIG_HOSTS='debug'
# For release build:
BUILD_CONFIG_HOSTS='CONFIG+=release\ CONFIG-=debug'

### END Editable part

export REMOTE_USER_ROUTER
export REMOTE_HOST_ROUTER
export REMOTE_PORT_ROUTER
export REMOTE_DEDICATED_IP_ROUTER
export REMOTE_DEDICATED_IF_ROUTER
export BUILD_CONFIG_ROUTER
export REMOTE_USER_HOSTS
export REMOTE_HOST_HOSTS
export REMOTE_PORT_HOSTS
export REMOTE_DEDICATED_IP_HOSTS
export REMOTE_DEDICATED_IF_HOSTS
export BUILD_CONFIG_HOSTS

echo '#!/bin/sh'
echo '### Configuration:'
echo "SRC_DIR=$SRC_DIR"
echo "REMOTE_USER_ROUTER=$REMOTE_USER_ROUTER"
echo "REMOTE_HOST_ROUTER=$REMOTE_HOST_ROUTER"
echo "REMOTE_PORT_ROUTER=$REMOTE_PORT_ROUTER"
echo "REMOTE_DEDICATED_IP_ROUTER=$REMOTE_DEDICATED_IP_ROUTER"
echo "REMOTE_DEDICATED_IF_ROUTER=$REMOTE_DEDICATED_IF_ROUTER"
echo "BUILD_CONFIG_ROUTER=$BUILD_CONFIG_ROUTER"
echo "REMOTE_USER_HOSTS=$REMOTE_USER_HOSTS"
echo "REMOTE_HOST_HOSTS=$REMOTE_HOST_HOSTS"
echo "REMOTE_PORT_HOSTS=$REMOTE_PORT_HOSTS"
echo "REMOTE_DEDICATED_IP_HOSTS=$REMOTE_DEDICATED_IP_HOSTS"
echo "REMOTE_DEDICATED_IF_HOSTS=$REMOTE_DEDICATED_IF_HOSTS"
echo "BUILD_CONFIG_HOSTS=$BUILD_CONFIG_HOSTS"
echo "INSTALL_PF_RING=$INSTALL_PF_RING"

HEADER="$SRC_DIR/remote_config.h"
if [ ! -f "$HEADER" ] || test "$SRC_DIR/remote-config.sh" -nt "$HEADER"
then
  echo "" > "$HEADER"
  echo "/* Automatically generated by $SRC_DIR/remote-config.sh, edit that script instead */" >> "$HEADER"
  echo "#define SRC_DIR \"$SRC_DIR\"" >> "$HEADER"
  echo "#define REMOTE_USER_ROUTER \"$REMOTE_USER_ROUTER\"" >> "$HEADER"
  echo "#define REMOTE_HOST_ROUTER \"$REMOTE_HOST_ROUTER\"" >> "$HEADER"
  echo "#define REMOTE_PORT_ROUTER \"$REMOTE_PORT_ROUTER\"" >> "$HEADER"
  echo "#define REMOTE_DEDICATED_IP_ROUTER \"$REMOTE_DEDICATED_IP_ROUTER\"" >> "$HEADER"
  echo "#define REMOTE_DEDICATED_IF_ROUTER \"$REMOTE_DEDICATED_IF_ROUTER\"" >> "$HEADER"
  echo "#define BUILD_CONFIG_ROUTER \"$BUILD_CONFIG_ROUTER\"" >> "$HEADER"
  echo "#define REMOTE_USER_HOSTS \"$REMOTE_USER_HOSTS\"" >> "$HEADER"
  echo "#define REMOTE_HOST_HOSTS \"$REMOTE_HOST_HOSTS\"" >> "$HEADER"
  echo "#define REMOTE_PORT_HOSTS \"$REMOTE_PORT_HOSTS\"" >> "$HEADER"
  echo "#define REMOTE_DEDICATED_IP_HOSTS \"$REMOTE_DEDICATED_IP_HOSTS\"" >> "$HEADER"
  echo "#define REMOTE_DEDICATED_IF_HOSTS \"$REMOTE_DEDICATED_IF_HOSTS\"" >> "$HEADER"
  echo "#define BUILD_CONFIG_HOSTS \"$BUILD_CONFIG_HOSTS\"" >> "$HEADER"
  echo "#define INSTALL_PF_RING \"$INSTALL_PF_RING\"" >> "$HEADER"
fi
